AWSTemplateFormatVersion: "2010-09-09"
Description: "Fixing EC2 Instance Availability Zone Issue"

Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: "10.0.1.0/24"
      AvailabilityZone: !Select [0, !GetAZs ""] # Automatically selects the first AZ in the region

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08b5b3a93ed654d19 # Ensure this AMI is valid for your region
      InstanceType: t2.micro
      SubnetId: !Ref MySubnet # Subnet determines the AZ automatically
